export const uploadContent = jest.fn(() => 'not-a-real-url')
export const uploadAvatar = jest.fn(() => 'not-a-real-avatar-url')
export const deleteContent = jest.fn()
export const getContentMetadata = jest.fn(() => { return { size: 12 } })
export const convertCDNUrlToS3Key = jest.fn(() => 'https://cdn.com/key')