
FROM node:12.13.0-alpine

# The base node image sets a very verbose log level.
ENV NPM_CONFIG_LOGLEVEL warn

WORKDIR /api

# Only copy package.json first to take advantage of docker caching
COPY package*.json ./

RUN npm install

# .dockerignore ensures not everything is copied
COPY . .

RUN npm run build

RUN rm -rf node_modules/
RUN rm -rf src/

ENV NODE_ENV production
RUN npm install --only=production

ENTRYPOINT ["/bin/sh", "./run.sh"]