const ACTIONS = {
  READ: 'READ',
  LIST: 'LIST',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  CREATE: 'CREATE',
  UPDATE_ORG_ROLE: 'UPDATE_ORG_ROLE',
  READ_MY: 'READ_MY',
  LIST_MY: 'LIST_MY',
  UPDATE_MY: 'UPDATE_MY',
  UPDATE_MY_BILLING: 'UPDATE_MY_BILLING',
  READ_MY_BILLING: 'READ_MY_BILLING'
}

export default ACTIONS