const RESOURCE_TYPES = {
  USER: 'USER',
  PROJECT: 'PROJECT',
  DOCUMENT: 'DOCUMENT',
  PROJECT_USER: 'PROJECT_USER'
}

export const PROJECT_RESOURCE_TYPES = [RESOURCE_TYPES.PROJECT, RESOURCE_TYPES.DOCUMENT]

export default RESOURCE_TYPES