const RESOURCE_TYPES = {
  USER: 'USER',
  PROJECT: 'PROJECT',
  DOCUMENT: 'DOCUMENT',
  PROJECT_USER: 'PROJECT_USER',
  FIELD: 'FIELD',
  PROJECT_TOKEN: 'PROJECT_TOKEN'
}

export const PROJECT_RESOURCE_TYPES = [
  RESOURCE_TYPES.PROJECT,
  RESOURCE_TYPES.DOCUMENT,
  RESOURCE_TYPES.FIELD
]

export default RESOURCE_TYPES
