const RESOURCE_TYPES = {
  USER: 'USER',
  PROJECT: 'PROJECT',
  DOCUMENT: 'DOCUMENT',
  PROJECT_USER: 'PROJECT_USER',
  FIELD: 'FIELD',
  FIELD_ORDER: 'FIELD_ORDER',
  PROJECT_TOKEN: 'PROJECT_TOKEN',
  ORGANIZATION: 'ORGANIZATION',
  ROLE: 'ROLE',
  PASSWORD: 'PASSWORD',
  SEAT: 'SEAT',
  PROJECT_EXPORT: 'PROJECT_EXPORT',
  WEBHOOK: 'WEBHOOK',
  WEBHOOK_DELIVERY: 'WEBHOOK_DELIVERY'
}

export const PROJECT_RESOURCE_TYPES = [
  RESOURCE_TYPES.PROJECT,
  RESOURCE_TYPES.DOCUMENT,
  RESOURCE_TYPES.FIELD,
  RESOURCE_TYPES.PROJECT_USER,
  RESOURCE_TYPES.PROJECT_TOKEN,
  RESOURCE_TYPES.FIELD_ORDER,
  RESOURCE_TYPES.PROJECT_EXPORT,
  RESOURCE_TYPES.WEBHOOK,
  RESOURCE_TYPES.WEBHOOK_DELIVERY
]

export default RESOURCE_TYPES
