# Use builder image to install build dependencies
FROM node:12.18 as builder

# The base node image sets a very verbose log level.
ENV NPM_CONFIG_LOGLEVEL warn

WORKDIR /api

# Only copy package.json first to take advantage of docker caching
COPY package*.json ./

RUN npm install

# .dockerignore ensures not everything is copied
COPY . .

RUN npm run build

RUN rm -rf node_modules/
RUN rm -rf src/

ENV NODE_ENV production
RUN npm install --only=production

# Use empty app image for runtime dependencies only
FROM node:12.18 as app

COPY --from=builder /api .

ENV NODE_ENV production

ENTRYPOINT ["/bin/bash", "./run.sh"]