FROM node:12.18-stretch-slim as builder

# The base node image sets a very verbose log level.
ENV NPM_CONFIG_LOGLEVEL warn

WORKDIR /web

# Only copy package.json first to take advantage of docker caching
COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build
RUN rm -rf node_modules/
RUN rm -rf src/
RUN rm -rf config/

FROM node:12.18-stretch-slim as app

COPY --from=builder /web .

ENV NODE_ENV production
RUN npm install --only=production

ENTRYPOINT ["/bin/sh", "./run.sh"]
